apiVersion: v1
kind: Service
metadata:
  name: fleet-driver-svc
  namespace: {{ .Values.namespace | quote }}
spec:
  selector:
    app: fleet-driver
  ports:
    - name: http
      port: {{ .Values.driver.service.port }}
      targetPort: {{ .Values.driver.service.targetPort }}
  type: {{ .Values.driver.service.type }}
